import { 
  PostalStamp, 
  KeepsakeItem, 
  UserContact, 
  PublicStory, 
  WorldSeason,
  PigeonClothing,
  BottleGlassColor,
  WaxInsignia,
  LetterNotification
} from '../types';

export const PIGEON_NAMES: string[] = [
  'Homer',
  'Barnaby',
  'Persephone',
  'Pip',
  'Archibald',
  'Clover',
  'Gulliver',
  'Winston',
  'Zephyr',
  'Rowan',
  'Atticus',
  'Bramble',
  'Caspian',
  'Penelope',
  'Bram',
  'Orville',
  'Felix',
  'Jasper',
  'Linus',
  'Ophelia'
];

export function getRandomPigeonName(): string {
  return PIGEON_NAMES[Math.floor(Math.random() * PIGEON_NAMES.length)];
}

export const PIGEON_CLOTHING_OPTIONS: PigeonClothing[] = [
  {
    id: 'aviator_goggles',
    name: 'Aviator Goggles & Cap',
    description: 'Leather flight cap & brass goggles for high cloud ceilings',
    icon: '👓',
    color: '#b45309',
  },
  {
    id: 'knitted_scarf',
    name: 'Woolen Amber Scarf',
    description: 'Hand-knit mustard wool scarf to ward off mountain drafts',
    icon: '🧣',
    color: '#d97706',
  },
  {
    id: 'postal_satchel',
    name: 'Leather Post Satchel',
    description: 'Weathered miniature mail pouch with tiny brass buckle',
    icon: '👜',
    color: '#78350f',
  },
  {
    id: 'royal_cape',
    name: 'Crimson Royal Cape',
    description: 'Velvet courier mantle with gilded hem threads',
    icon: '👑',
    color: '#991b1b',
  },
  {
    id: 'sailor_collar',
    name: 'Navy Sailor Neckerchief',
    description: 'Crisp indigo nautical knot for maritime routes',
    icon: '⚓',
    color: '#1e3a8a',
  },
  {
    id: 'laurel_wreath',
    name: 'Botanical Laurel Wreath',
    description: 'Woven wild olive leaves & pressed mountain heather',
    icon: '🌿',
    color: '#065f46',
  },
  {
    id: 'cozy_sweater',
    name: 'Cozy Fair Isle Knit',
    description: 'Snug woodland green sweater for autumnal headwinds',
    icon: '🧶',
    color: '#047857',
  },
  {
    id: 'brass_compass',
    name: 'Compass Chest Harness',
    description: 'Gimbaled miniature magnetic compass secured with rawhide',
    icon: '🧭',
    color: '#d97706',
  },
  {
    id: 'natural_plumage',
    name: 'Natural Slate Plumage',
    description: 'Classic iridescent neck feathers and slate-gray wings',
    icon: '🕊️',
    color: '#64748b',
  },
];

export const BOTTLE_GLASS_COLORS: BottleGlassColor[] = [
  {
    id: 'seafoam',
    name: 'Seafoam Emerald',
    hex: '#14b8a6',
    description: 'Tumbled ocean glass reminiscent of shallow tidal pools',
  },
  {
    id: 'cobalt',
    name: 'Cobalt Sapphire',
    hex: '#2563eb',
    description: 'Deep maritime glass that glints blue in direct sunlight',
  },
  {
    id: 'amber',
    name: 'Warm Antique Amber',
    hex: '#d97706',
    description: 'Apothecary sun-kissed glass with golden honey reflections',
  },
  {
    id: 'amethyst',
    name: 'Smoked Amethyst',
    hex: '#9333ea',
    description: 'Mysterious twilight violet, steeped in evening shadows',
  },
  {
    id: 'frosted',
    name: 'Frosted Salt Mist',
    hex: '#94a3b8',
    description: 'Weathered pale glass softened by decades of shoreline sand',
  },
  {
    id: 'rose_quartz',
    name: 'Pale Rose Quartz',
    hex: '#f472b6',
    description: 'Gentle blush glass resembling dawn over calm waters',
  },
  {
    id: 'obsidian',
    name: 'Midnight Obsidian',
    hex: '#334155',
    description: 'Smoky charcoal flask that conceals the parchment inside',
  },
];

export const WAX_INSIGNIAS: WaxInsignia[] = [
  { id: 'swallow', name: 'Carrier Swallow', symbol: '🕊️', lore: 'Faithful return and enduring flight' },
  { id: 'anchor', name: 'Admiralty Anchor', symbol: '⚓', lore: 'Steadfast through rough oceanic swells' },
  { id: 'compass', name: 'Compass Rose', symbol: '🧭', lore: 'True heading across unmapped horizons' },
  { id: 'swell', name: 'Tidal Crest', symbol: '🌊', lore: 'Surrendering to the ocean’s gentle rhythm' },
  { id: 'moon', name: 'Crescent Moon', symbol: '🌙', lore: 'Nocturnal guidance and quiet contemplation' },
  { id: 'lighthouse', name: 'Solitary Beacon', symbol: '🕯️', lore: 'A watchful lamp through midnight fog' },
  { id: 'fern', name: 'Forest Fern', symbol: '🌿', lore: 'Quiet solace and grounded patience' },
];

export const INITIAL_NOTIFICATIONS: LetterNotification[] = [
  {
    id: 'notif-1',
    type: 'letter_received',
    title: 'Carrier Pigeon Landed at Your Windowsill',
    message: 'A slate homer named "Homer" has touched down at your hearth with a letter from Clara Vance in Lisbon.',
    timestamp: 'Day 36',
    dateNumber: 36,
    letterId: 'letter-init-1',
    flightId: 'pigeon-flight-delivered',
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'letter_delivered',
    title: 'Your Letter Reached Edinburgh Haven',
    message: 'Your pigeon "Barnaby" safely navigated the Cheviot Hills and landed on Julian Thorne’s lighthouse sill!',
    timestamp: 'Day 38',
    dateNumber: 38,
    letterId: 'letter-in-flight',
    flightId: 'pigeon-flight-1',
    isRead: true,
  },
  {
    id: 'notif-3',
    type: 'bottle_washed_up',
    title: 'A Bottle Washed Ashore and Was Taken from the Tide',
    message: 'A stranger along the rocky sands discovered your drifting Seafoam bottle and broke the wax seal. It is no longer adrift on the map.',
    timestamp: 'Day 37',
    dateNumber: 37,
    letterId: 'letter-bottle-adrift',
    bottleId: 'bottle-adrift-1',
    isRead: true,
  },
];

export const POSTAL_STAMPS: PostalStamp[] = [
  {
    id: 'stamp-swallow',
    name: 'Migratory Swallow 5¢',
    denomination: '5¢',
    theme: 'Safe Passage',
    color: '#1e3a8a',
    iconName: 'Feather',
    quote: 'Across stormy skies, the heart finds its homeward heading.',
  },
  {
    id: 'stamp-lighthouse',
    name: 'Cape Solitude 10¢',
    denomination: '10¢',
    theme: 'Guiding Light',
    color: '#b45309',
    iconName: 'Compass',
    quote: 'A steadfast lamp through midnight sea mist.',
  },
  {
    id: 'stamp-fern',
    name: 'Pressed Silver Fern 3¢',
    denomination: '3¢',
    theme: 'Quiet Solace',
    color: '#065f46',
    iconName: 'TreePine',
    quote: 'Green memories gathered in silent mountain groves.',
  },
  {
    id: 'stamp-constellation',
    name: 'Nocturnal Ursa 20¢',
    denomination: '20¢',
    theme: 'Celestial Navigation',
    color: '#4c1d95',
    iconName: 'Moon',
    quote: 'Steering unhurried by ancient celestial beacons.',
  },
  {
    id: 'stamp-nautilus',
    name: 'Tidal Nautilus 12¢',
    denomination: '12¢',
    theme: 'Drift & Patience',
    color: '#0f766e',
    iconName: 'Shell',
    quote: 'What is entrusted to the deep ocean returns in its own hour.',
  },
  {
    id: 'stamp-ginkgo',
    name: 'Autumn Ginkgo 8¢',
    denomination: '8¢',
    theme: 'Endurance',
    color: '#c2410c',
    iconName: 'Wind',
    quote: 'Leaves adrift upon the pond of time.',
  },
];

export const KEEPSAKES: KeepsakeItem[] = [
  {
    id: 'ks-seaglass',
    name: 'Frosted Sea Glass',
    type: 'sea_glass',
    lore: 'Tumbled smooth by thirty years of shoreline surf off the cliffs of Big Sur.',
  },
  {
    id: 'ks-fern',
    name: 'Pressed Woodland Fern',
    type: 'pressed_fern',
    lore: 'Harvested in the morning mist of an ancient misty cedar forest.',
  },
  {
    id: 'ks-shell',
    name: 'Pale Spiral Shell',
    type: 'seashell',
    lore: 'A quiet souvenir washed onto pebble shores after a winter squall.',
  },
  {
    id: 'ks-pine',
    name: 'Balsam Pine Needle Cluster',
    type: 'pine_needle',
    lore: 'Carries the crisp resinous scent of high maritime headlands.',
  },
  {
    id: 'ks-lavender',
    name: 'Sprig of Dried Lavender',
    type: 'lavender',
    lore: 'Dried between pages of a botany sketchbook in late August.',
  },
  {
    id: 'ks-coin',
    name: 'Smooth Copper Token',
    type: 'copper_coin',
    lore: 'An untraceable ferry token smoothed by countless hands and pocket friction.',
  },
];

export const DEFAULT_CONTACTS: UserContact[] = [
  {
    id: 'contact-clara',
    name: 'Clara Vance',
    company: 'Lisbon Botanical Institute',
    position: 'Lead Herbarium Researcher',
    city: 'Lisbon',
    region: 'Tagus Estuary, Portugal',
    coords: { x: 44, y: 35 },
    lastLetterDate: '18 days ago',
    lettersExchanged: 6,
    relation: 'Old botanical friend',
  },
  {
    id: 'contact-julian',
    name: 'Julian Thorne',
    company: 'Northern Lighthouse Board',
    position: 'Chief Keeper & Archival Historian',
    city: 'Edinburgh',
    region: 'Firth of Forth, Scotland',
    coords: { x: 47, y: 22 },
    lastLetterDate: '43 days ago',
    lettersExchanged: 9,
    relation: 'Lighthouse keeper & historian',
  },
  {
    id: 'contact-moriko',
    name: 'Moriko Tanaka',
    company: 'Kamo River Ceramic Studios',
    position: 'Master Ceramicist & Kiln Director',
    city: 'Kyoto',
    region: 'Kamo River Basin, Japan',
    coords: { x: 82, y: 39 },
    lastLetterDate: '2 months ago',
    lettersExchanged: 4,
    relation: 'Tea artisan & ceramicist',
  },
  {
    id: 'contact-silas',
    name: 'Silas Ward',
    company: 'Atlantic Cartography Bureau',
    position: 'Senior Maritime Hydrographer',
    city: 'Halifax',
    region: 'Nova Scotia, Canada',
    coords: { x: 30, y: 32 },
    lastLetterDate: 'Yesterday',
    lettersExchanged: 2,
    relation: 'Maritime navigator',
  },
  {
    id: 'contact-maya',
    name: 'Maya Ruiz',
    company: 'Valparaíso Press Guild',
    position: 'Principal Bookbinder & Conservator',
    city: 'Valparaíso',
    region: 'Cerro Alegre, Chile',
    coords: { x: 33, y: 78 },
    lastLetterDate: '5 months ago',
    lettersExchanged: 1,
    relation: 'Poet & bookbinder',
  },
];

export const CAREER_INDUSTRIES = [
  'Open to All Professions',
  'Software & Technology',
  'Architecture & Spatial Design',
  'Medicine & Healthcare',
  'Literature & Publishing',
  'Science, Ecology & Botany',
  'Craftsmanship & Artisan Trades',
  'Maritime, Cartography & Navigation',
  'Arts, Music & Film',
  'Finance, Law & Governance',
  'Philosophy & Education',
] as const;

export const CAREER_POSITIONS_BY_INDUSTRY: Record<string, string[]> = {
  'Software & Technology': [
    'Senior Software Engineer',
    'Distributed Systems Architect',
    'Open-Source Maintainer',
    'Product Designer',
    'AI Systems Researcher',
    'Security Cryptographer',
  ],
  'Architecture & Spatial Design': [
    'Principal Architect',
    'Landscape Urbanist',
    'Historical Restorer',
    'Timber Frame Craftsman',
    'Interior Acoustic Designer',
  ],
  'Medicine & Healthcare': [
    'Emergency Trauma Physician',
    'Holistic Apothecary & Herbalist',
    'Clinical Neuroscientist',
    'Midwife & Care Practitioner',
    'Chief Medical Officer',
  ],
  'Literature & Publishing': [
    'Literary Novelist',
    'Independent Book Publisher',
    'Poet & Broadside Printer',
    'Manuscript Editor',
    'Archival Essayist',
  ],
  'Science, Ecology & Botany': [
    'Marine Oceanographer',
    'Herbarium Botanist',
    'Glaciologist & Climate Observer',
    'Mycology Researcher',
    'Astrophysicist',
  ],
  'Craftsmanship & Artisan Trades': [
    'Master Ceramicist',
    'Heritage Blacksmith',
    'Bookbinder & Leatherworker',
    'Master Horologist (Watchmaker)',
    'Loom Weaver & Textile Dyer',
  ],
  'Maritime, Cartography & Navigation': [
    'Lighthouse Keeper',
    'Deep-Water Harbor Pilot',
    'Nautical Cartographer',
    'Wooden Vessel Shipwright',
    'Ocean Passage Navigator',
  ],
  'Arts, Music & Film': [
    'Acoustic Composer',
    'Botanical Illustrator',
    'Cinematographer & Documentarian',
    'Printmaker & Etcher',
    'Sculptor & Stonemason',
  ],
  'Finance, Law & Governance': [
    'Public Interest Advocate',
    'Sustainable Finance Steward',
    'Diplomatic Envoy',
    'Maritime Trade Arbitrator',
    'Civic Urban Planner',
  ],
  'Philosophy & Education': [
    'University Professor',
    'Philosophy Fellow',
    'Librarian & Rare Books Curator',
    'Montessori Educator',
    'Natural History Docent',
  ],
};

export interface MatchingProfessional {
  name: string;
  position: string;
  company: string;
  industry: string;
  location: string;
}

export const MATCHING_PROFESSIONALS: MatchingProfessional[] = [
  {
    name: 'Ada Lovelace-Vance',
    position: 'Distributed Systems Architect',
    company: 'Open Kernel Conservatory',
    industry: 'Software & Technology',
    location: 'Cambridge Observatory Cove',
  },
  {
    name: 'Linus Sterling',
    position: 'Senior Software Engineer',
    company: 'Northern Lights Computing Guild',
    industry: 'Software & Technology',
    location: 'Reykjavik Fjord Haven',
  },
  {
    name: 'Siddharth Rao',
    position: 'Open-Source Maintainer',
    company: 'Global Network Fellowship',
    industry: 'Software & Technology',
    location: 'Goa Coastal Bay',
  },
  {
    name: 'Evelyn St. Claire',
    position: 'Principal Architect',
    company: 'Atelier St. Claire',
    industry: 'Architecture & Spatial Design',
    location: 'Sintra Granite Cliffs',
  },
  {
    name: 'Mateo Morales',
    position: 'Historical Restorer',
    company: 'Iberian Heritage Trust',
    industry: 'Architecture & Spatial Design',
    location: 'Seville Riverbank Basin',
  },
  {
    name: 'Dr. Aris Thorne',
    position: 'Emergency Trauma Physician',
    company: 'Royal Infirmary of Edinburgh',
    industry: 'Medicine & Healthcare',
    location: 'Firth of Forth Haven',
  },
  {
    name: 'Dr. Amara Sen',
    position: 'Clinical Neuroscientist',
    company: 'Cerebral Dynamics Institute',
    industry: 'Medicine & Healthcare',
    location: 'Kerala Backwaters Clinic',
  },
  {
    name: 'Cassian Vane',
    position: 'Manuscript Editor',
    company: 'Broadside & Quarto Press',
    industry: 'Literature & Publishing',
    location: 'Oxford Meadow Reach',
  },
  {
    name: 'Beatrix Shaw',
    position: 'Poet & Broadside Printer',
    company: 'Whalebone Letterpress',
    industry: 'Literature & Publishing',
    location: 'Whitby Harbor Pier',
  },
  {
    name: 'Dr. Thais Beaumont',
    position: 'Marine Oceanographer',
    company: 'Brest Hydrographic Station',
    industry: 'Science, Ecology & Botany',
    location: 'Brittany Tide Basins',
  },
  {
    name: 'Liam O’Connell',
    position: 'Herbarium Botanist',
    company: 'Kew Royal Herbarium',
    industry: 'Science, Ecology & Botany',
    location: 'Thames Estuary Reach',
  },
  {
    name: 'Mikhail Voronin',
    position: 'Master Horologist (Watchmaker)',
    company: 'Chronos Heritage Atelier',
    industry: 'Craftsmanship & Artisan Trades',
    location: 'Geneva Lakeside Pier',
  },
  {
    name: 'Soren Lindqvist',
    position: 'Lighthouse Keeper',
    company: 'Scandinavian Coast Beacon Service',
    industry: 'Maritime, Cartography & Navigation',
    location: 'Lofoten Archipelago Watch',
  },
  {
    name: 'Captain Corina Del Mar',
    position: 'Deep-Water Harbor Pilot',
    company: 'Valparaíso Maritime Directorate',
    industry: 'Maritime, Cartography & Navigation',
    location: 'Cerro Alegre Headland',
  },
  {
    name: 'Isolde Faulkner',
    position: 'Acoustic Composer',
    company: 'Chamber Resonance Society',
    industry: 'Arts, Music & Film',
    location: 'Salzburg Alpine Valley',
  },
  {
    name: 'Helena Berg',
    position: 'Public Interest Advocate',
    company: 'Maritime Human Rights Council',
    industry: 'Finance, Law & Governance',
    location: 'The Hague Coastal Haven',
  },
  {
    name: 'Professor Arthur Pendelton',
    position: 'Rare Books Curator & Docent',
    company: 'Bodleian Special Collections',
    industry: 'Philosophy & Education',
    location: 'Isis Riverbank Roost',
  },
];

export const SEASONS: WorldSeason[] = [
  {
    name: 'Autumn Equinox Mist',
    flywayCondition: 'Favorable tailwinds across Atlantic lowlands; cool foggy river mouths.',
    seaCurrentSpeed: 'Steady 2.8 knots northeast on the Gulf Stream.',
    windPattern: 'Gentle westerlies with intermittent coastal drizzle.',
    pigeonSafetyBonus: 0.04,
  },
  {
    name: 'Winter Solstice Gales',
    flywayCondition: 'Turbulent squalls over mountain divides; pigeons rest longer in belfries.',
    seaCurrentSpeed: 'Fast 3.6 knots through tempest swells.',
    windPattern: 'Brisk polar northerlies driving bottles south into trade latitudes.',
    pigeonSafetyBonus: -0.06,
  },
  {
    name: 'Spring Thermal Awakening',
    flywayCondition: 'Soaring thermals over sunlit pine ridges; flock migrations active.',
    seaCurrentSpeed: 'Calm 2.1 knots in coastal shoals.',
    windPattern: 'Soft southerly breezes bearing flower fragrance.',
    pigeonSafetyBonus: 0.08,
  },
  {
    name: 'Summer Twilight Doldrums',
    flywayCondition: 'Long warm twilights; flight windows optimal during dawn and evening.',
    seaCurrentSpeed: 'Placid 1.8 knots in the great central gyres.',
    windPattern: 'Balmy maritime breezes, peaceful starry nights.',
    pigeonSafetyBonus: 0.02,
  },
];

export const NOTABLE_STORIES: PublicStory[] = [
  {
    id: 'story-1',
    title: 'The Tagus Flagon: Three Oceans in a Blue Glass Vial',
    author: 'An Anonymous Cobbler of Lisbon',
    route: 'Cast from Belém Pier → Washed ashore on Tahiti Reef',
    driftDays: 824,
    excerpt: '“I cast this into the tide on the night my daughter took the morning train to Paris. If you find this, whisper to the water that I have learned to listen to the empty rooms.”',
    fullChronicle: 'Released on a damp November dusk in 2023, the cobalt vial slipped past the Cabo da Roca headland into the Canary Current. It was pulled across the doldrums into the South Atlantic gyre, circumnavigated the Cape of Good Hope, and rode the equatorial drift until coral fishers in Tahiti spotted its wax-sealed neck caught in a mangrove root after 824 days of silence.',
    recoveredLocation: 'Tahiti, French Polynesia',
    oceanCurrent: 'South Equatorial Current',
    tags: ['Family', 'Patience', '824 Days', 'Pacific'],
  },
  {
    id: 'story-2',
    title: 'A Songbird’s Winter Sanctuary',
    author: 'Carrier Pigeon ‘Boreas-7’ (Reported by Father Anselm)',
    route: 'Edinburgh → St. Michael’s Mount Cloisters',
    driftDays: 31,
    excerpt: '“The slate-grey pigeon landed on our refectory ledge during compline, its leather quill capsule dripping with sea rain.”',
    fullChronicle: 'Carrying a dispatch intended for Cornwall, the bird was swept off course by a North Sea squall. Instead of despairing, it rested for twelve days in the belfry of a Benedictine monastery, fed on dried barley by monks, before completing the final 90 miles across Dartmoor in glorious morning sunlight.',
    recoveredLocation: 'St. Michael’s Mount, Cornwall',
    oceanCurrent: 'Atlantic Coastal Flyway',
    tags: ['Pigeon Post', 'Storm Rescue', 'Epistolary Wonder'],
  },
  {
    id: 'story-3',
    title: 'The Pressed Meadow of Hokkaido',
    author: 'K. from Otaru',
    route: 'Otaru Port, Sea of Japan → Mendocino Headlands, California',
    driftDays: 512,
    excerpt: '“Between these pages is a single petal from my grandmother’s persimmon tree. It has now crossed the greatest ocean on earth.”',
    fullChronicle: 'Travelled the Kuroshio Current along the Aleutian trench before looping south through the California Current. Discovered by an author walking her dog at sunrise among driftwood logs in Mendocino. The seal remained completely watertight.',
    recoveredLocation: 'Mendocino, California',
    oceanCurrent: 'North Pacific Gyre & California Current',
    tags: ['Botanical', 'Pacific Drift', 'Keepsake'],
  },
];
